# Generated by Django 4.2.7 on 2024-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://luigispizzakenosha.com/wp-content/uploads/placeholder.png', max_length=500),
        ),
    ]
